### ISSUE TITLE
Got a warnning in getInitialProps with a promise.

### ISSUE THREAD

**Issue by robert7git** [ykfe/egg-react-ssr#10]
## version
```json
{
  ykfe-util:  "^1.1.0" 
}
```

I do like this:

```js
Page.getInitialProps = () => {
  console.log('👽  Page.getInitialProps');
  return api.products.list().then(data => ({
    products: data,
  }));
};
```

api.products.list is like this:
return new Promise((resolve, reject) => {
      return fetch(
        `${APISERVERHOST}/api/${this.name}.json?page=${option.page}&per_page=${option.perPage}`
      )
        .then(response => {
          if (response.status >= 400) {
            reject('Bad response from server');
          }
          return resolve(response.json());
        })
        .then(data => {
          return data;
        })
        .catch(err => {
          throw new Error(err);
        });
    });

and got warnning:
``` 
WARNING in ./node_modules/ykfe-utils/es/renderToStream.js 34:25-60
[1] Critical dependency: the request of a dependency is an expression
[1]  @ ./node_modules/ykfe-utils/es/index.js
[1]  @ ./web/entry.js
[1] Child html-webpack-plugin for "index.html":
```

**Comment by zhangyuang** [comment]
@robert7git 
hi, the warning because of the require path in renderToStream is an expression
for example,most of the time, we use require is require('../index.js')
but in this App, we need set something is configurable，so we use require(config.path)
so, webpack-dev-server prompt this warning。
you can use webpack-dev-server --client-log-level error to show error level log in package.json
we will use this config as default config in next version
