### ISSUE TITLE
HtmlWebpackPlugin

### ISSUE THREAD

**Issue by gromov-io** [ykfe/egg-react-ssr#143]
how to use HtmlWebpackPlugin hashing correctly ? I add two files in the webpack configuration [hash].chunk.the css Assembly does not automatically process hashed files, but in config.ssr.js can't add them.

**Comment by zhangyuang** [comment]
No need to use HtmlWebpackPlugin it's not recommend, the program implement all is jsx。
i recommend you using version tag instead of hash because it against version traceback。
you can refer the doc mine wrote [the best publish way](http://ykfe.net/guide/deploy.html)
if you still want to use hash chunk, may be you can read dist/assets-manifest.json and get the correct hash files
![image](https://user-images.githubusercontent.com/17424434/72001196-e2786d80-327f-11ea-8d9c-29607cc6e879.png)

**Comment by zhangyuang** [comment]
@gromov-io if it works, welcome to help us propagate the repo out of china,i think many of foreigner will love it。but it's difficult for us because our English is not so good and  don't join foreign community
