### ISSUE TITLE
针对layout优化还是不太理解

### ISSUE THREAD

**Issue by xiaokyo** [ykfe/egg-react-ssr#205]
就是我layout只需要渲染一遍，客户端跳转的时候不用去重新渲染及重新进行里面的请求，如何才能优雅的实现

**Comment by zhangyuang** [comment]
不同页面的layout是新的实例是正常的。具体怎么控制layout要做哪些逻辑开发者自己在layout决定
判断一下path再发请求

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaokyo <notifications@github.com&gt;
发送时间: 2020年12月19日 21:05
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 针对layout优化还是不太理解 (#205)





 
就是我layout只需要渲染一遍，客户端跳转的时候不用去重新渲染及重新进行里面的请求，如何才能优雅的实现

**Comment by xiaokyo** [comment]
> 不同页面的layout是新的实例是正常的。具体怎么控制layout要做哪些逻辑开发者自己在layout决定 判断一下path再发请求 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: xiaokyo <notifications@github.com&gt; 发送时间: 2020年12月19日 21:05 收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[ykfe/egg-react-ssr] 针对layout优化还是不太理解 (#205) 就是我layout只需要渲染一遍，客户端跳转的时候不用去重新渲染及重新进行里面的请求，如何才能优雅的实现 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

layout新实例，数据那岂不是要放在类似redux数据管理，不然每个layout子页面切换都是会新载入，有什么推荐方法嘛，我现在摸不着头绪

**Comment by zhangyuang** [comment]
可以放dva，也可以直接挂window检查window没有再重新请求。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaokyo <notifications@github.com&gt;
发送时间: 2020年12月19日 21:52
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 针对layout优化还是不太理解 (#205)





  
不同页面的layout是新的实例是正常的。具体怎么控制layout要做哪些逻辑开发者自己在layout决定 判断一下path再发请求 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: xiaokyo <notifications@github.com&gt; 发送时间: 2020年12月19日 21:05 收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[ykfe/egg-react-ssr] 针对layout优化还是不太理解 (#205) 就是我layout只需要渲染一遍，客户端跳转的时候不用去重新渲染及重新进行里面的请求，如何才能优雅的实现 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
layout新实例，数据那岂不是要放在类似redux数据管理，不然每个layout子页面切换都是会新载入，有什么推荐方法嘛，我现在摸不着头绪

**Comment by xiaokyo** [comment]
> 可以放dva，也可以直接挂window检查window没有再重新请求。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: xiaokyo <notifications@github.com&gt; 发送时间: 2020年12月19日 21:52 收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; 抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[ykfe/egg-react-ssr] 针对layout优化还是不太理解 (#205) 不同页面的layout是新的实例是正常的。具体怎么控制layout要做哪些逻辑开发者自己在layout决定 判断一下path再发请求 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: xiaokyo <notifications@github.com&gt; 发送时间: 2020年12月19日 21:05 收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[ykfe/egg-react-ssr] 针对layout优化还是不太理解 (#205) 就是我layout只需要渲染一遍，客户端跳转的时候不用去重新渲染及重新进行里面的请求，如何才能优雅的实现 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. layout新实例，数据那岂不是要放在类似redux数据管理，不然每个layout子页面切换都是会新载入，有什么推荐方法嘛，我现在摸不着头绪 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，明白了

**Comment by xiaokyo** [comment]
我像了解下客户端的getInitialProps的入参，我没看到那块逻辑代码，是在哪个地方

**Comment by zhangyuang** [comment]
ykfe-utils的高阶组件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaokyo <notifications@github.com&gt;
发送时间: 2020年12月20日 10:48
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 针对layout优化还是不太理解 (#205)





 
我像了解下客户端的getInitialProps的入参，我没看到那块逻辑代码，是在哪个地方

**Comment by xiaokyo** [comment]
> ykfe-utils的高阶组件 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: xiaokyo <notifications@github.com&gt; 发送时间: 2020年12月20日 10:48 收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; 抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[ykfe/egg-react-ssr] 针对layout优化还是不太理解 (#205) 我像了解下客户端的getInitialProps的入参，我没看到那块逻辑代码，是在哪个地方 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢你的耐心回答
